apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bastion-pvc
  namespace: bastion
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: scw-bssd