apiVersion: v1
kind: PersistentVolume
metadata:
  name: bastion-pv
  namespace: bastion
spec:
  storageClassName: scw-bssd
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt"
  claimRef:
    name: bastion-pvc
    namespace: bastion
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bastion-pvc
  namespace: bastion
  labels:
    app: bastion
spec:
  volumeName: bastion-pv
  storageClassName: scw-bssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
