apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-prod
  namespace: production
spec:
  storageClassName: scw-bssd
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: "/data/db"
  claimRef:
    name: mongodb-pvc-prod
    namespace: production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-prod
  namespace: production
spec:
  volumeName: mongodb-pv-prod
  storageClassName: scw-bssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi