apiVersion: v1
kind: Service
metadata:
  name: mongodb-prod
  namespace: production
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb-prod
  clusterIP: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-prod
  namespace: production
spec:
  selector:
    matchLabels:
      app: mongodb-prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb-prod
    spec:
      hostname: mongodb-prod
      containers:
      - image: mongo:5
        name: mongodb-prod
        ports:
        - containerPort: 27017
          name: mongodb-prod
        volumeMounts:
        - name: mongodb-prod-persistent-storage
          mountPath: /data/db
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mongodb-prod-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc-prod
