apiVersion: v1
kind: Service
metadata:
  name: mariadb-prod
  namespace: production
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-prod
  namespace: production
spec:
  selector:
    matchLabels:
      app: mariadb-prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb-prod
    spec:
      containers:
      - image: mariadb:10
        name: mariadb-prod
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-prod-root-password
              key: password
        ports:
        - containerPort: 3306
          name: mariadb-prod
        volumeMounts:
        - name: mariadb-prod-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mariadb-prod-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc-prod
