kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: mariadb
  name: mariadb-direct
  namespace: production
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 31006
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb